# Generated by Django 3.1.1 on 2020-09-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_preference',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Subscribed'), (2, 'Unsubscribed')], default=1),
        ),
    ]
