# Generated by Django 3.1.2 on 2020-10-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20200915_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Subscribed'), (2, 'Unsubscribed')], default=2),
        ),
    ]
