# Generated by Django 3.1.1 on 2020-09-09 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_is_subscribed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows', '0002_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='subscribers',
            field=models.ManyToManyField(through='subscriptions.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
