# Generated by Django 3.1.1 on 2020-09-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_show_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
