# Generated by Django 3.1.1 on 2020-09-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
