# Generated by Django 3.1.1 on 2020-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='first_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='last_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
