# Generated by Django 3.1.1 on 2020-09-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20200923_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('first_name', 'last_name', 'show')},
        ),
    ]
