# Generated by Django 3.1.1 on 2020-09-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20200923_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
    ]
