# Generated by Django 3.1.1 on 2020-09-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_remove_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='number',
        ),
    ]
