# Generated by Django 3.1.1 on 2020-09-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_remove_episode_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('name', 'season', 'show')},
        ),
    ]
