# Generated by Django 3.1.2 on 2020-10-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20200924_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Movie'), (2, 'TV')], default=0),
        ),
    ]
