# Generated by Django 3.1.2 on 2020-10-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_show_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='status',
            new_name='category',
        ),
    ]
