# Generated by Django 3.1.2 on 2020-10-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_auto_20201025_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
