# Generated by Django 3.1.1 on 2020-09-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shows', '0004_show_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(unique=True)),
                ('speaker_name', models.CharField(max_length=255)),
                ('season_number', models.CharField(max_length=255)),
                ('episode_number', models.CharField(max_length=255)),
                ('episode_title', models.CharField(max_length=255)),
                ('show_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.show')),
            ],
        ),
    ]
