# Generated by Django 3.1.1 on 2020-09-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='episode_title',
            field=models.CharField(max_length=256),
        ),
    ]
