# Generated by Django 3.1.1 on 2020-09-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200923_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='episode_title',
        ),
    ]
