# Generated by Django 3.1.1 on 2020-09-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20200923_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='show_name',
        ),
    ]
