# Generated by Django 3.1.1 on 2020-09-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quote_show_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_text',
            new_name='quote',
        ),
    ]
