# Generated by Django 3.1.1 on 2020-09-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20200923_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='text',
        ),
    ]
