# Generated by Django 3.1.1 on 2020-09-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_remove_character_name'),
        ('quotes', '0008_auto_20200923_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='speaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shows.character'),
            preserve_default=False,
        ),
    ]
