# Generated by Django 3.1.2 on 2020-10-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20200924_0651'),
        ('quotes', '0010_remove_quote_speaker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shows.episode'),
        ),
    ]
